### ISSUE TITLE
UI is inactive if tool is opened with an already connected environment

### ISSUE THREAD

**Issue by FH-Inway** [crmgustaf/BulkDeleteManager#2]
Gave this tool a test drive today, works great so far.

One hickup though: When I'm already connected to an environment (e.g. because I was using another tool) and then open the Bulk Delete Manager, the UI of the tool stays inactive as shown in the screenshot.
Workaround is to restart XrmToolBox and then open the Bulk Delete Manager tool first, which causes the connection to be established. In that case, the build delete jobs are loaded and the UI becomes active.

XrmToolBox version is 1.2022.5.56. Bulk Delete Manager tool version is 1.0.1.2

![image](https://user-images.githubusercontent.com/33372796/172794941-80e0a76a-c08c-4462-b0c5-74a740755377.png)

**Comment by crmgustaf** [comment]
Thanks! We will have a look at this!

**Comment by femo1de** [comment]
Doesn't seem to be working even with the workaround. It doesnt matter whether I restart the toolbox and then do a fresh connect or change the connection with the tool open. I just can't get it to become active no matter what

**Comment by mihails-simvulidi** [comment]
For me it recovers after several minutes. If the tool retrieves the data or so it should notify the user that it's in process of loading.

**Comment by crmgustaf** [comment]
Hi,
Yes, I am working on a new version of this. Trying to get a better user experience when it loads the metadata which does take some time and also make it not crash when loading, depending on how you open the tool (all ways should work of course).

**Comment by crmgustaf** [comment]
Just rolled out a new version 1.0.2, where I have rewritten the loading part. Should be a lot faster and more stable too.
