### ISSUE TITLE
When scheduling a recurring deletion job the tool does not allow you schedule it at a time after 12:00 AM

### ISSUE THREAD

**Issue by Jeronimo70** [crmgustaf/BulkDeleteManager#3]
When scheduling a recurring deletion job the tool does not allow you schedule it at a time after 12:00 AM. There is no way to indicate AM/PM or 24:oo timestamp

**Comment by mihails-simvulidi** [comment]
The same for me.

**Comment by crmgustaf** [comment]
Hi,
Yes, I have noticed this bug. There is some issue with the date-time control which makes it not able to set the time correctly.

Will fix this in the new version we are working on.

**Comment by crmgustaf** [comment]
This should be fixed now in version 1.0.2, just released.
