### ISSUE TITLE
Not possible to create a one-time job

### ISSUE THREAD

**Issue by mihails-simvulidi** [crmgustaf/BulkDeleteManager#4]
It isn't possible to change recurrency pattern to "None". If I leave interval 0, it still creates a daily job, so I have to manually cancel it after it launches for the first time. I cannot use the built-in Power Apps functionality because it doesn't support some FetchXML options such as [left outer join to query for records "not in"](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/use-fetchxml-left-outer-join-query-records-not-in) and doesn't support deleting records from some system tables such as Import Source Files.

**Comment by crmgustaf** [comment]
Hi,
Yes, this is true. We will try to fix this in the new version we are working on.
