### ISSUE TITLE
I can't update to 1.0.2

### ISSUE THREAD

**Issue by rappen** [crmgustaf/BulkDeleteManager#5]
Something fishy here...

![image](https://github.com/crmgustaf/BulkDeleteManager/assets/2572253/cb1902da-1171-4959-8c55-42702a397ac3)

Selecting the latest version, and the buttons are never enabled.

---
- Deployment: Online
- DB Version: 9.2.23051.240
- Connection Controls Version: 1.2023.2.55
- XrmToolBox Version: 1.2023.3.64
- Tool Version: 1.0.1.2

**Comment by crmgustaf** [comment]
This should be fixed now.
